# Generated by Django 4.2.5 on 2023-11-04 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuildNestApp', '0004_alter_usertable_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='is_admin',
        ),
    ]
